import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CalendarDays,ChevronLeft,ChevronRight,PiggyBank,TrendingUp} from 'lucide-react';
import * as api from './api';
import './annual.css';

const months=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const compact=(v:number)=>v===0?'—':v.toLocaleString('pt-BR',{maximumFractionDigits:0});
const n=(v:string)=>Number(v)||0;
type CategoryRow={id:string;name:string;planned:number[];actual:number[]};

export default function AnnualPlan(){
  const currentYear=new Date().getFullYear();
  const[year,setYear]=useState(currentYear+1);
  const[opening,setOpening]=useState(()=>n(localStorage.getItem('cashflow_annual_opening')||'10000'));
  const[reserve,setReserve]=useState(()=>n(localStorage.getItem('cashflow_annual_reserve')||'10000'));
  const[selectedMonth,setSelectedMonth]=useState(0);
  const[projection,setProjection]=useState<api.Projection|null>(null);
  const[budgets,setBudgets]=useState<(api.Budget|null)[]>([]);
  const[loading,setLoading]=useState(false);

  async function load(){setLoading(true);localStorage.setItem('cashflow_annual_opening',String(opening));localStorage.setItem('cashflow_annual_reserve',String(reserve));try{const[p,b]=await Promise.all([api.getProjection(year,1,12,opening),Promise.all(Array.from({length:12},(_,i)=>api.getBudget(year,i+1).catch(()=>null)))]);setProjection(p);setBudgets(b)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);

  const summary=useMemo(()=>{const m=projection?.months??[];const income=m.reduce((s,x)=>s+x.totalIncomeAmount,0);const expense=m.reduce((s,x)=>s+x.totalExpenseAmount,0);const result=m.reduce((s,x)=>s+x.netAmount,0);const lowest=m.length?m.reduce((a,b)=>a.closingBalance<=b.closingBalance?a:b):null;const negative=m.filter(x=>x.closingBalance<0);return{income,expense,result,lowest,negative,final:projection?.finalBalance??opening}},[projection,opening]);
  const categoryRows=useMemo(()=>{const map=new Map<string,CategoryRow>();budgets.forEach((b,mi)=>b?.categories?.forEach(c=>{let row=map.get(c.categoryId);if(!row){row={id:c.categoryId,name:c.categoryName,planned:Array(12).fill(0),actual:Array(12).fill(0)};map.set(c.categoryId,row)}row.planned[mi]=c.plannedAmount;row.actual[mi]=c.actualAmount}));return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))},[budgets]);
  const month=projection?.months[selectedMonth];const budget=budgets[selectedMonth];const planned=budget?.plannedAmount??0;const availableAboveReserve=month?month.closingBalance-reserve:0;

  return <section className="annual-plan">
    <div className="annual-hero"><div className="annual-heading"><span className="section-kicker">PLANEJAMENTO DO ANO</span><h2>Como seu dinheiro deve se comportar em {year}</h2><p>Planejado, realizado e projeção futura no mesmo lugar — sem transformar o CashFlow em uma planilha estática.</p></div><div className="annual-settings"><label>Ano<input type="number" value={year} onChange={e=>setYear(+e.target.value)}/></label><label>Saldo inicial<input type="number" step="0.01" value={opening} onChange={e=>setOpening(+e.target.value)}/></label><label>Reserva mínima<input type="number" step="0.01" value={reserve} onChange={e=>setReserve(+e.target.value)}/></label><button className="primary-button" onClick={load} disabled={loading}>{loading?'Calculando...':'Recalcular ano'}</button></div></div>

    <div className="annual-summary"><div><span>Entradas previstas</span><strong>{money(summary.income)}</strong><small>No ano inteiro</small></div><div><span>Saídas previstas</span><strong>{money(summary.expense)}</strong><small>Recorrências + cartões + despesas</small></div><div><span>Resultado anual</span><strong className={summary.result<0?'negative-text':'positive-text'}>{money(summary.result)}</strong><small>Entradas menos saídas</small></div><div><span>Saldo final</span><strong className={summary.final<0?'negative-text':'positive-text'}>{money(summary.final)}</strong><small>Com saldo inicial</small></div></div>

    <div className={`annual-health ${summary.negative.length?'annual-health-bad':'annual-health-good'}`}><div className="health-icon">{summary.negative.length?<AlertTriangle/>:<TrendingUp/>}</div><div><strong>{summary.negative.length?`${summary.negative.length} mês(es) exigem atenção`:'Nenhum mês termina negativo'}</strong><span>{summary.negative.length?`Primeiro alerta: ${months[(summary.negative[0]?.month??1)-1]} com ${money(summary.negative[0]?.closingBalance??0)}.`:`A projeção permanece positiva em ${year}.`}</span></div>{summary.lowest&&<div className="health-low"><span>Pior saldo</span><strong>{months[summary.lowest.month-1]} · {money(summary.lowest.closingBalance)}</strong></div>}</div>

    <article className="panel annual-matrix-panel"><div className="panel-title"><div><span className="section-kicker">PLANEJADO × REALIZADO</span><h2>Orçamento anual por categoria</h2><p>As linhas vêm do orçamento já cadastrado. Cada mês mostra planejado e realizado.</p></div></div>{categoryRows.length?<div className="annual-matrix-wrap"><table className="annual-matrix"><thead><tr><th rowSpan={2}>Categoria</th>{months.map(m=><th key={m} colSpan={2}>{m}</th>)}<th colSpan={2}>Ano</th></tr><tr>{months.flatMap(m=>[<th key={`${m}-p`}>Plan.</th>,<th key={`${m}-r`}>Real.</th>])}<th>Plan.</th><th>Real.</th></tr></thead><tbody>{categoryRows.map(row=>{const yp=row.planned.reduce((a,b)=>a+b,0),ya=row.actual.reduce((a,b)=>a+b,0);return <tr key={row.id}><th>{row.name}</th>{months.flatMap((_,i)=>[<td key={`${i}-p`}>{compact(row.planned[i])}</td>,<td key={`${i}-a`} className={row.actual[i]>row.planned[i]&&row.planned[i]>0?'over':''}>{compact(row.actual[i])}</td>])}<td className="year-cell">{compact(yp)}</td><td className={`year-cell ${ya>yp&&yp>0?'over':''}`}>{compact(ya)}</td></tr>})}<tr className="matrix-total"><th>TOTAL DESPESAS</th>{months.flatMap((_,i)=>{const p=categoryRows.reduce((s,r)=>s+r.planned[i],0),a=categoryRows.reduce((s,r)=>s+r.actual[i],0);return[<td key={`${i}-tp`}>{compact(p)}</td>,<td key={`${i}-ta`}>{compact(a)}</td>]})}<td>{compact(categoryRows.reduce((s,r)=>s+r.planned.reduce((a,b)=>a+b,0),0))}</td><td>{compact(categoryRows.reduce((s,r)=>s+r.actual.reduce((a,b)=>a+b,0),0))}</td></tr></tbody></table></div>:<div className="annual-empty">Nenhum orçamento por categoria cadastrado para {year}. A projeção financeira abaixo continua funcionando com lançamentos, recorrências e cartões.</div>}</article>

    <article className="panel annual-timeline-panel"><div className="panel-title"><div><span className="section-kicker">PROJEÇÃO MÊS A MÊS</span><h2>Resultado e saldo acumulado</h2><p>O fechamento de um mês continua sendo a abertura do próximo.</p></div></div><div className="annual-month-strip">{projection?.months.map((x,i)=><button key={`${x.year}-${x.month}`} className={`${selectedMonth===i?'active':''} ${x.closingBalance<0?'negative':''}`} onClick={()=>setSelectedMonth(i)}><span>{months[i]}</span><strong>{money(x.closingBalance)}</strong><small>{x.netAmount<0?'Déficit':'Sobra'} {money(Math.abs(x.netAmount))}</small></button>)}</div></article>

    {month&&<section className="annual-detail-grid"><article className="panel annual-month-card"><div className="month-card-top"><button className="month-arrow" aria-label="Mês anterior" onClick={()=>setSelectedMonth(Math.max(0,selectedMonth-1))} disabled={selectedMonth===0}><ChevronLeft/></button><div><span className="section-kicker">DETALHE DO MÊS</span><h2>{months[selectedMonth]} {year}</h2><p>O que entra, sai e como o mês termina.</p></div><button className="month-arrow" aria-label="Próximo mês" onClick={()=>setSelectedMonth(Math.min(11,selectedMonth+1))} disabled={selectedMonth===11}><ChevronRight/></button></div><div className="month-flow"><div><span>Saldo abertura</span><strong>{money(month.openingBalance)}</strong></div><div className="income"><span>+ Receitas</span><strong>{money(month.totalIncomeAmount)}</strong></div><div className="expense"><span>− Despesas</span><strong>{money(month.totalExpenseAmount)}</strong></div><div className="month-result"><span>Saldo fechamento</span><strong className={month.closingBalance<0?'negative-text':'positive-text'}>{money(month.closingBalance)}</strong></div></div></article>
    <article className="panel annual-explain-card"><div className="panel-title"><div><span className="section-kicker">COMPOSIÇÃO</span><h2>De onde vem o resultado</h2></div></div><div className="annual-breakdown"><div><span>Receitas normais</span><strong>{money(month.incomeAmount)}</strong></div><div><span>Receitas recorrentes</span><strong>{money(month.recurringIncomeAmount)}</strong></div><div><span>Despesas diretas</span><strong>{money(month.directExpenseAmount)}</strong></div><div><span>Despesas recorrentes</span><strong>{money(month.recurringExpenseAmount)}</strong></div><div><span>Cartões e parcelas</span><strong>{money(month.creditCardAmount)}</strong></div></div></article>
    <article className="panel annual-control-card"><div className="panel-title"><div><span className="section-kicker">SEGURANÇA</span><h2>Reserva e orçamento</h2></div><PiggyBank/></div><div className="control-highlight"><span>Excedente acima da reserva</span><strong className={availableAboveReserve<0?'negative-text':'positive-text'}>{money(availableAboveReserve)}</strong><small>{availableAboveReserve<0?'A reserva mínima seria consumida neste mês.':'Valor livre depois de proteger sua reserva.'}</small></div><div className="annual-breakdown compact"><div><span>Reserva mínima</span><strong>{money(reserve)}</strong></div><div><span>Planejado no mês</span><strong>{money(planned)}</strong></div><div><span>Realizado no orçamento</span><strong>{money(budget?.actualAmount??0)}</strong></div></div></article></section>}

    <div className="annual-help"><CalendarDays size={18}/><p><strong>Leitura:</strong> orçamento mostra planejado × realizado; projeção incorpora também receitas, recorrências e parcelas futuras para antecipar o saldo dos próximos meses.</p></div>
  </section>
}
