import {FormEvent,useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CalendarDays,ChevronLeft,ChevronRight,PiggyBank,Plus,TrendingUp,X} from 'lucide-react';
import * as api from './api';
import './annual.css';
import './annual-editor.css';

const months=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const compact=(v:number)=>v===0?'—':v.toLocaleString('pt-BR',{maximumFractionDigits:0});
const n=(v:string)=>Number(v)||0;
type CategoryRow={id:string;name:string;planned:number[];actual:number[]};
type PlannedMonth=api.MonthlyBalance&{plannedGap:number};

export default function AnnualPlan(){
 const currentYear=new Date().getFullYear();
 const[year,setYear]=useState(currentYear+1),[opening,setOpening]=useState(()=>n(localStorage.getItem('cashflow_annual_opening')||'10000')),[reserve,setReserve]=useState(()=>n(localStorage.getItem('cashflow_annual_reserve')||'10000')),[selectedMonth,setSelectedMonth]=useState(0);
 const[projection,setProjection]=useState<api.Projection|null>(null),[budgets,setBudgets]=useState<(api.Budget|null)[]>([]),[categories,setCategories]=useState<api.Category[]>([]),[loading,setLoading]=useState(false);
 const[editorOpen,setEditorOpen]=useState(false),[editorCategory,setEditorCategory]=useState(''),[editorValues,setEditorValues]=useState<number[]>(Array(12).fill(0)),[saving,setSaving]=useState(false),[error,setError]=useState('');

 async function load(){setLoading(true);setError('');localStorage.setItem('cashflow_annual_opening',String(opening));localStorage.setItem('cashflow_annual_reserve',String(reserve));try{const[p,b,c]=await Promise.all([api.getProjection(year,1,12,opening),Promise.all(Array.from({length:12},(_,i)=>api.getBudget(year,i+1).catch(()=>null)),api.getCategories()]);setProjection(p);setBudgets(b);setCategories(c.filter(x=>x.type===2&&x.isActive))}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar planejamento')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);

 const categoryRows=useMemo(()=>{const map=new Map<string,CategoryRow>();budgets.forEach((b,mi)=>b?.categories?.forEach(c=>{let row=map.get(c.categoryId);if(!row){row={id:c.categoryId,name:c.categoryName,planned:Array(12).fill(0),actual:Array(12).fill(0)};map.set(c.categoryId,row)}row.planned[mi]=c.plannedAmount;row.actual[mi]=c.actualAmount}));return[...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))},[budgets]);
 const plannedMonths=useMemo<PlannedMonth[]>(()=>{if(!projection)return[];let balance=opening;return projection.months.map((base,i)=>{const budget=budgets[i];const gap=Math.max(0,(budget?.plannedAmount??0)-(budget?.actualAmount??0));const totalExpense=base.totalExpenseAmount+gap;const net=base.totalIncomeAmount-totalExpense;const closing=balance+net;const result={...base,openingBalance:balance,totalExpenseAmount:totalExpense,netAmount:net,closingBalance:closing,isNegative:closing<0,plannedGap:gap};balance=closing;return result})},[projection,budgets,opening]);
 const summary=useMemo(()=>{const m=plannedMonths;const income=m.reduce((s,x)=>s+x.totalIncomeAmount,0),expense=m.reduce((s,x)=>s+x.totalExpenseAmount,0),result=income-expense;const lowest=m.length?m.reduce((a,b)=>a.closingBalance<=b.closingBalance?a:b):null,negative=m.filter(x=>x.closingBalance<0);return{income,expense,result,lowest,negative,final:m.at(-1)?.closingBalance??opening}},[plannedMonths,opening]);
 const month=plannedMonths[selectedMonth],budget=budgets[selectedMonth],planned=budget?.plannedAmount??0,availableAboveReserve=month?month.closingBalance-reserve:0;

 function openNew(){setEditorCategory('');setEditorValues(Array(12).fill(0));setEditorOpen(true)}
 function openRow(row:CategoryRow){setEditorCategory(row.id);setEditorValues([...row.planned]);setEditorOpen(true)}
 function repeat(value:number){setEditorValues(Array(12).fill(value))}
 async function savePlan(e:FormEvent){e.preventDefault();if(!editorCategory)return;setSaving(true);setError('');try{await Promise.all(editorValues.map((value,i)=>api.setBudget({year,month:i+1,categoryId:editorCategory,plannedAmount:value})));setEditorOpen(false);await load()}catch(err){setError(err instanceof Error?err.message:'Falha ao salvar planejamento')}finally{setSaving(false)}}

 return <section className="annual-plan">
  <div className="annual-hero"><div className="annual-heading"><span className="section-kicker">PLANEJAMENTO ORÇAMENTÁRIO</span><h2>Decida hoje como {year} deve acontecer</h2><p>Monte cenários, inclua compras futuras e acompanhe o impacto no caixa antes de assumir um compromisso.</p></div><div className="annual-settings"><label>Ano<input type="number" value={year} onChange={e=>setYear(+e.target.value)}/></label><label>Saldo inicial<input type="number" step="0.01" value={opening} onChange={e=>setOpening(+e.target.value)}/></label><label>Reserva mínima<input type="number" step="0.01" value={reserve} onChange={e=>setReserve(+e.target.value)}/></label><button className="primary-button" onClick={load} disabled={loading}>{loading?'Calculando...':'Recalcular ano'}</button></div></div>
  {error&&<div className="error">{error}</div>}
  <div className="annual-summary"><div><span>Receitas previstas</span><strong>{money(summary.income)}</strong><small>Receitas conhecidas no ano</small></div><div><span>Despesas + planejamento</span><strong>{money(summary.expense)}</strong><small>Compromissos e valores ainda planejados</small></div><div><span>Resultado anual</span><strong className={summary.result<0?'negative-text':'positive-text'}>{money(summary.result)}</strong><small>Receitas menos despesas</small></div><div><span>Saldo projetado final</span><strong className={summary.final<0?'negative-text':'positive-text'}>{money(summary.final)}</strong><small>Já considera o orçamento futuro</small></div></div>
  <div className={`annual-health ${summary.negative.length?'annual-health-bad':'annual-health-good'}`}><div className="health-icon">{summary.negative.length?<AlertTriangle/>:<TrendingUp/>}</div><div><strong>{summary.negative.length?`${summary.negative.length} mês(es) exigem atenção`:'Planejamento financeiramente sustentável'}</strong><span>{summary.negative.length?`Primeiro alerta: ${months[(summary.negative[0]?.month??1)-1]} fecha em ${money(summary.negative[0]?.closingBalance??0)}.`:`Com o que está planejado, nenhum mês termina negativo em ${year}.`}</span></div>{summary.lowest&&<div className="health-low"><span>Pior saldo</span><strong>{months[summary.lowest.month-1]} · {money(summary.lowest.closingBalance)}</strong></div>}</div>

  <article className="panel annual-matrix-panel"><div className="panel-title annual-plan-title"><div><span className="section-kicker">PLANEJADO × REALIZADO</span><h2>Plano orçamentário {year}</h2><p>Crie uma linha para cada decisão: lazer, escola, viagem, carro, obra ou qualquer categoria de despesa.</p></div><button className="annual-plan-add" onClick={openNew}><Plus size={17}/>Planejar categoria</button></div>{categoryRows.length?<div className="annual-matrix-wrap"><table className="annual-matrix"><thead><tr><th rowSpan={2}>Categoria</th>{months.map(m=><th key={m} colSpan={2}>{m}</th>)}<th colSpan={2}>Ano</th></tr><tr>{months.flatMap(m=>[<th key={`${m}-p`}>Plan.</th>,<th key={`${m}-r`}>Real.</th>])}<th>Plan.</th><th>Real.</th></tr></thead><tbody>{categoryRows.map(row=>{const yp=row.planned.reduce((a,b)=>a+b,0),ya=row.actual.reduce((a,b)=>a+b,0);return <tr key={row.id} onClick={()=>openRow(row)} className="editable-row"><th>{row.name}</th>{months.flatMap((_,i)=>[<td key={`${i}-p`}>{compact(row.planned[i])}</td>,<td key={`${i}-a`} className={row.actual[i]>row.planned[i]&&row.planned[i]>0?'over':''}>{compact(row.actual[i])}</td>])}<td className="year-cell">{compact(yp)}</td><td className={`year-cell ${ya>yp&&yp>0?'over':''}`}>{compact(ya)}</td></tr>})}<tr className="matrix-total"><th>TOTAL PLANEJADO</th>{months.flatMap((_,i)=>{const p=categoryRows.reduce((s,r)=>s+r.planned[i],0),a=categoryRows.reduce((s,r)=>s+r.actual[i],0);return[<td key={`${i}-tp`}>{compact(p)}</td>,<td key={`${i}-ta`}>{compact(a)}</td>]})}<td>{compact(categoryRows.reduce((s,r)=>s+r.planned.reduce((a,b)=>a+b,0),0))}</td><td>{compact(categoryRows.reduce((s,r)=>s+r.actual.reduce((a,b)=>a+b,0),0))}</td></tr></tbody></table></div>:<div className="annual-empty"><strong>Comece seu planejamento de {year}</strong><span>Ex.: crie a categoria “Carro”, informe R$ 60.000 em julho e veja imediatamente como essa decisão afeta o restante do ano.</span><button className="annual-plan-add" onClick={openNew}><Plus size={17}/>Criar primeiro planejamento</button></div>}</article>

  <article className="panel annual-timeline-panel"><div className="panel-title"><div><span className="section-kicker">IMPACTO NO CAIXA</span><h2>Resultado e saldo acumulado</h2><p>Além dos compromissos reais, considera o que ainda falta gastar do orçamento planejado.</p></div></div><div className="annual-month-strip">{plannedMonths.map((x,i)=><button key={`${x.year}-${x.month}`} className={`${selectedMonth===i?'active':''} ${x.closingBalance<0?'negative':''}`} onClick={()=>setSelectedMonth(i)}><span>{months[i]}</span><strong>{money(x.closingBalance)}</strong><small>{x.netAmount<0?'Déficit':'Sobra'} {money(Math.abs(x.netAmount))}</small></button>)}</div></article>

  {month&&<section className="annual-detail-grid"><article className="panel annual-month-card"><div className="month-card-top"><button className="month-arrow" onClick={()=>setSelectedMonth(Math.max(0,selectedMonth-1))} disabled={selectedMonth===0}><ChevronLeft/></button><div><span className="section-kicker">DETALHE DO MÊS</span><h2>{months[selectedMonth]} {year}</h2><p>Resultado já considerando o planejamento ainda não realizado.</p></div><button className="month-arrow" onClick={()=>setSelectedMonth(Math.min(11,selectedMonth+1))} disabled={selectedMonth===11}><ChevronRight/></button></div><div className="month-flow"><div><span>Saldo abertura</span><strong>{money(month.openingBalance)}</strong></div><div className="income"><span>+ Receitas</span><strong>{money(month.totalIncomeAmount)}</strong></div><div className="expense"><span>− Saídas previstas</span><strong>{money(month.totalExpenseAmount)}</strong></div><div className="month-result"><span>Saldo fechamento</span><strong className={month.closingBalance<0?'negative-text':'positive-text'}>{money(month.closingBalance)}</strong></div></div></article><article className="panel annual-explain-card"><div className="panel-title"><div><span className="section-kicker">COMPOSIÇÃO</span><h2>De onde vem o resultado</h2></div></div><div className="annual-breakdown"><div><span>Receitas normais</span><strong>{money(month.incomeAmount)}</strong></div><div><span>Receitas recorrentes</span><strong>{money(month.recurringIncomeAmount)}</strong></div><div><span>Despesas diretas</span><strong>{money(month.directExpenseAmount)}</strong></div><div><span>Despesas recorrentes</span><strong>{money(month.recurringExpenseAmount)}</strong></div><div><span>Cartões e parcelas</span><strong>{money(month.creditCardAmount)}</strong></div><div className="planned-gap"><span>Planejado ainda não realizado</span><strong>{money(month.plannedGap)}</strong></div></div></article><article className="panel annual-control-card"><div className="panel-title"><div><span className="section-kicker">SEGURANÇA</span><h2>Reserva e orçamento</h2></div><PiggyBank/></div><div className="control-highlight"><span>Excedente acima da reserva</span><strong className={availableAboveReserve<0?'negative-text':'positive-text'}>{money(availableAboveReserve)}</strong><small>{availableAboveReserve<0?'O plano invade sua reserva mínima neste mês.':'Valor livre depois de proteger sua reserva.'}</small></div><div className="annual-breakdown compact"><div><span>Reserva mínima</span><strong>{money(reserve)}</strong></div><div><span>Planejado no mês</span><strong>{money(planned)}</strong></div><div><span>Realizado</span><strong>{money(budget?.actualAmount??0)}</strong></div></div></article></section>}

  <div className="annual-help"><CalendarDays size={18}/><p><strong>Exemplo:</strong> antes de comprar um carro, planeje o valor no mês desejado. O CashFlow combina essa decisão com recorrências, parcelas e lançamentos já conhecidos e mostra se o caixa e a reserva suportam a compra.</p></div>

  {editorOpen&&<div className="modern-modal-backdrop"><section className="modern-modal annual-editor"><div className="modern-modal-head"><div><span className="section-kicker">PLANEJAR {year}</span><h2>Planejamento por categoria</h2><p>Informe quanto pretende gastar em cada mês.</p></div><button onClick={()=>setEditorOpen(false)}><X/></button></div><form className="modern-form" onSubmit={savePlan}><label>Categoria<select value={editorCategory} onChange={e=>{const id=e.target.value;setEditorCategory(id);const row=categoryRows.find(x=>x.id===id);setEditorValues(row?[...row.planned]:Array(12).fill(0))}} required><option value="">Escolha uma categoria de despesa</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="annual-editor-tools"><span>Mesmo valor todos os meses:</span><input type="number" min="0" step="0.01" placeholder="R$ 0,00" onBlur={e=>{const v=Number(e.target.value)||0;if(v>0)repeat(v)}}/></div><div className="annual-month-inputs">{months.map((m,i)=><label key={m}>{m}<input type="number" min="0" step="0.01" value={editorValues[i]||''} placeholder="0,00" onChange={e=>setEditorValues(v=>v.map((x,j)=>j===i?(Number(e.target.value)||0):x))}/></label>)}</div><div className="annual-editor-total"><span>Total planejado no ano</span><strong>{money(editorValues.reduce((a,b)=>a+b,0))}</strong></div><div className="modern-actions"><button type="button" className="modern-cancel" onClick={()=>setEditorOpen(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?'Salvando...':'Salvar planejamento'}</button></div></form></section></div>}
 </section>
}
