import {FormEvent,useMemo,useState,type ReactNode} from 'react';
import {ArrowRight,Check,ChevronLeft,CircleDollarSign,CreditCard,Landmark,PartyPopper,Plus,Repeat2,Sparkles,WalletCards} from 'lucide-react';
import * as api from './api';
import './onboarding.css';

type Props={onFinish:()=>void;onSkip:()=>void};
type RecurringDraft={description:string;amount:number;day:number;category:string};
type LoanDraft={description:string;installment:number;remaining:number;day:number};
type CardDraft={name:string;limit:number;closingDay:number;dueDay:number};
type PurchaseDraft={cardId:string;description:string;installment:number;remaining:number;category:string};

const nextOccurrence=(day:number)=>{const now=new Date();const d=new Date(now.getFullYear(),now.getMonth(),Math.min(Math.max(day,1),28),12);if(d<now)d.setMonth(d.getMonth()+1);return d};
const addMonths=(date:Date,count:number)=>{const d=new Date(date);d.setMonth(d.getMonth()+count);return d};
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default function OnboardingWizard({onFinish,onSkip}:Props){
 const[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const[accounts,setAccounts]=useState<api.Account[]>([]),[cards,setCards]=useState<api.Card[]>([]);
 const[created,setCreated]=useState({accounts:0,incomes:0,expenses:0,loans:0,cards:0,purchases:0});
 const[account,setAccount]=useState({name:'Conta principal',type:1,balance:0});
 const[income,setIncome]=useState<RecurringDraft>({description:'Salário',amount:0,day:5,category:'Salário'});
 const[expense,setExpense]=useState<RecurringDraft>({description:'',amount:0,day:10,category:''});
 const[loan,setLoan]=useState<LoanDraft>({description:'',installment:0,remaining:12,day:10});
 const[card,setCard]=useState<CardDraft>({name:'',limit:0,closingDay:20,dueDay:28});
 const[purchase,setPurchase]=useState<PurchaseDraft>({cardId:'',description:'',installment:0,remaining:2,category:''});
 const total=created.accounts+created.incomes+created.expenses+created.loans+created.cards+created.purchases;
 const pct=Math.round((Math.max(step,1)/6)*100);
 const accountId=accounts.find(x=>x.isActive)?.id??null;
 const summary=useMemo(()=>[{value:created.accounts,label:'contas'},{value:created.incomes+created.expenses+created.loans,label:'recorrências'},{value:created.cards,label:'cartões'},{value:created.purchases,label:'parceladas'}],[created]);
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Não consegui salvar. Tente novamente.')}finally{setBusy(false)}}
 async function getCategoryId(name:string,type:number){const clean=name.trim();if(!clean)return null;const list=await api.getCategories();const found=list.find(x=>x.isActive&&x.type===type&&x.name.toLocaleLowerCase('pt-BR')===clean.toLocaleLowerCase('pt-BR'));if(found)return found.id;return (await api.createCategory({name:clean,type})).id}
 async function createRecurring(d:RecurringDraft,type:number){const start=nextOccurrence(d.day),categoryId=await getCategoryId(d.category,type);await api.createRecurring({amount:d.amount,type,description:d.description.trim(),frequency:0,startAt:start.toISOString(),endAt:null,isActive:true,accountId,categoryId})}
 const next=()=>{setError('');setStep(s=>Math.min(7,s+1))};const back=()=>{setError('');setStep(s=>Math.max(0,s-1))};
 return <main className="onboarding-shell"><div className="onboarding-orb orb-a"/><div className="onboarding-orb orb-b"/><section className="onboarding-card"><header className="onboarding-header"><div className="onboarding-brand"><span><WalletCards size={20}/></span><strong>CashFlow</strong></div>{step>0&&step<7&&<button className="onboarding-skip" onClick={onSkip}>Entrar no app</button>}</header>{step>0&&step<7&&<div className="onboarding-progress" aria-label={`Progresso ${pct}%`}><div style={{width:`${pct}%`}}/></div>}<div className="onboarding-content">{error&&<div className="onboarding-error">{error}</div>}
 {step===0&&<div className="onboarding-hero"><div className="hero-icon"><Sparkles/></div><span className="onboarding-kicker">COMEÇO RÁPIDO</span><h1>Vamos montar sua vida financeira?</h1><p>Sem planilha e sem formulário gigante. Você responde coisas da vida real e eu organizo tudo no CashFlow.</p><div className="onboarding-benefits"><span><Check/> Uma pergunta por vez</span><span><Check/> Pode pular o que não tiver</span><span><Check/> Já alimenta sua projeção</span></div><button className="onboarding-primary full" onClick={next}>Bora começar <ArrowRight/></button><button className="onboarding-link" onClick={onSkip}>Prefiro cadastrar sozinho</button></div>}
 {step===1&&<Step icon={<WalletCards/>} kicker="1 · ONDE VOCÊ ESTÁ" title="Onde está seu dinheiro hoje?" text="Adicione suas contas e o saldo de hoje. Isso vira o ponto de partida da sua projeção."><form onSubmit={(e:FormEvent)=>{e.preventDefault();void run(async()=>{const a=await api.createAccount({name:account.name.trim(),type:account.type,initialBalance:account.balance});setAccounts(v=>[...v,a]);setCreated(v=>({...v,accounts:v.accounts+1}));setAccount({name:'',type:1,balance:0})})}}><label>Nome da conta<input value={account.name} onChange={e=>setAccount({...account,name:e.target.value})} placeholder="Ex.: BRB, Nubank, Carteira" required/></label><label>Saldo de hoje<MoneyInput value={account.balance} onChange={v=>setAccount({...account,balance:v})}/></label><label>Tipo<select value={account.type} onChange={e=>setAccount({...account,type:Number(e.target.value)})}><option value={1}>Conta corrente</option><option value={2}>Poupança</option><option value={3}>Dinheiro</option><option value={4}>Investimento</option><option value={99}>Outro</option></select></label><AddButton busy={busy}>Adicionar conta</AddButton></form><Created values={accounts.map(x=>`${x.name} · ${money(x.initialBalance)}`)}/><Continue onClick={next} disabled={!accounts.length}>Continuar</Continue></Step>}
 {step===2&&<Step icon={<CircleDollarSign/>} kicker="2 · O QUE ENTRA" title="O que cai todo mês?" text="Salário, aluguel, pensão, benefício... adicione quantos quiser."><RecurringForm draft={income} setDraft={setIncome} busy={busy} button="Adicionar renda" onSubmit={e=>{e.preventDefault();void run(async()=>{await createRecurring(income,1);setCreated(v=>({...v,incomes:v.incomes+1}));setIncome({description:'',amount:0,day:5,category:''})})}}/><Count value={created.incomes} text="renda mensal cadastrada"/><Continue onClick={next}>Não tenho mais / continuar</Continue></Step>}
 {step===4&&<Step icon={<Repeat2/>} kicker="4 · CONTAS DO MÊS" title="O que volta todo mês?" text="Escola, condomínio, internet, academia, aluguel... só o que lembrar agora."><RecurringForm draft={expense} setDraft={setExpense} busy={busy} button="Adicionar despesa" onSubmit={e=>{e.preventDefault();void run(async()=>{await createRecurring(expense,2);setCreated(v=>({...v,expenses:v.expenses+1}));setExpense({description:'',amount:0,day:10,category:''})})}}/><Count value={created.expenses} text="despesa recorrente cadastrada"/><Continue onClick={next}>Não tenho mais / continuar</Continue></Step>}
 {step===3&&<Step icon={<Landmark/>} kicker="3 · FINANCIAMENTOS" title="Tem parcelas que vão durar meses?" text="Casa, carro, consignado ou empréstimo. Informe só o que ainda falta pagar."><form onSubmit={(e:FormEvent)=>{e.preventDefault();void run(async()=>{const start=nextOccurrence(loan.day),end=addMonths(start,Math.max(loan.remaining-1,0)),categoryId=await getCategoryId('Financiamentos',2);await api.createRecurring({amount:loan.installment,type:2,description:loan.description.trim(),frequency:0,startAt:start.toISOString(),endAt:end.toISOString(),isActive:true,accountId,categoryId});setCreated(v=>({...v,loans:v.loans+1}));setLoan({description:'',installment:0,remaining:12,day:10})})}}><label>Qual é?<input value={loan.description} onChange={e=>setLoan({...loan,description:e.target.value})} placeholder="Ex.: Financiamento da casa" required/></label><div className="onboarding-grid"><label>Valor da parcela<MoneyInput value={loan.installment} onChange={v=>setLoan({...loan,installment:v})}/></label><label>Parcelas restantes<input type="number" min="1" value={loan.remaining} onChange={e=>setLoan({...loan,remaining:Number(e.target.value)})} required/></label><label>Vence dia<input type="number" min="1" max="28" value={loan.day} onChange={e=>setLoan({...loan,day:Number(e.target.value)})} required/></label></div><AddButton busy={busy}>Adicionar financiamento</AddButton></form><Count value={created.loans} text="financiamento cadastrado"/><Continue onClick={next}>Não tenho mais / continuar</Continue></Step>}
 {step===5&&<Step icon={<CreditCard/>} kicker="5 · CARTÕES" title="Quais cartões você usa?" text="Cadastre os cartões. No próximo passo eu pergunto das parcelas que já existem."><form onSubmit={(e:FormEvent)=>{e.preventDefault();void run(async()=>{const c=await api.createCard(card);setCards(v=>[...v,c]);setCreated(v=>({...v,cards:v.cards+1}));setPurchase(p=>({...p,cardId:p.cardId||c.id}));setCard({name:'',limit:0,closingDay:20,dueDay:28})})}}><label>Nome do cartão<input value={card.name} onChange={e=>setCard({...card,name:e.target.value})} placeholder="Ex.: BRB, Nubank" required/></label><label>Limite<MoneyInput value={card.limit} onChange={v=>setCard({...card,limit:v})}/></label><div className="onboarding-grid two"><label>Fecha dia<input type="number" min="1" max="28" value={card.closingDay} onChange={e=>setCard({...card,closingDay:Number(e.target.value)})}/></label><label>Vence dia<input type="number" min="1" max="28" value={card.dueDay} onChange={e=>setCard({...card,dueDay:Number(e.target.value)})}/></label></div><AddButton busy={busy}>Adicionar cartão</AddButton></form><Created values={cards.map(x=>x.name)}/><Continue onClick={next}>Não tenho mais / continuar</Continue></Step>}
 {step===6&&<Step icon={<CreditCard/>} kicker="6 · PARCELAS EXISTENTES" title={cards.length?'Tem compras parceladas em andamento?':'Sem cartão? Está tudo certo.'} text={cards.length?'Vamos registrar somente as parcelas que ainda faltam. Assim a previsão começa certa sem você reconstruir o passado.':'Você pode cadastrar cartões depois pelo botão +.'}>{cards.length>0&&<form onSubmit={(e:FormEvent)=>{e.preventDefault();void run(async()=>{const categoryId=await getCategoryId(purchase.category,2);await api.createPurchase({creditCardId:purchase.cardId||cards[0].id,categoryId,description:purchase.description.trim(),totalAmount:purchase.installment*purchase.remaining,installmentsCount:purchase.remaining,purchaseDate:new Date().toISOString()});setCreated(v=>({...v,purchases:v.purchases+1}));setPurchase(p=>({cardId:p.cardId,description:'',installment:0,remaining:2,category:''}))})}}><label>Cartão<select value={purchase.cardId||cards[0].id} onChange={e=>setPurchase({...purchase,cardId:e.target.value})}>{cards.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Compra<input value={purchase.description} onChange={e=>setPurchase({...purchase,description:e.target.value})} placeholder="Ex.: Material escolar" required/></label><div className="onboarding-grid two"><label>Valor da parcela<MoneyInput value={purchase.installment} onChange={v=>setPurchase({...purchase,installment:v})}/></label><label>Parcelas restantes<input type="number" min="1" value={purchase.remaining} onChange={e=>setPurchase({...purchase,remaining:Number(e.target.value)})} required/></label></div><label>Categoria <small>opcional</small><input value={purchase.category} onChange={e=>setPurchase({...purchase,category:e.target.value})} placeholder="Ex.: Educação, Casa, Lazer"/></label><AddButton busy={busy}>Adicionar compra parcelada</AddButton></form>}<Count value={created.purchases} text="compra parcelada cadastrada"/><Continue onClick={next}>Finalizar</Continue></Step>}
 {step===7&&<div className="onboarding-hero done"><div className="hero-icon success"><PartyPopper/></div><span className="onboarding-kicker">PRONTO 🎉</span><h1>Agora o CashFlow conhece sua realidade.</h1><p>{total?`Você já colocou ${total} ${total===1?'item':'itens'} para trabalhar na sua projeção.`:'Você pulou os cadastros. Sem problema: pode começar manualmente.'}</p><div className="onboarding-summary">{summary.map(x=><div key={x.label}><strong>{x.value}</strong><span>{x.label}</span></div>)}</div><button className="onboarding-primary full" onClick={onFinish}>Ver meu CashFlow <ArrowRight/></button></div>}</div>{step>0&&step<7&&<footer className="onboarding-footer"><button onClick={back}><ChevronLeft/> Voltar</button><span>Passo {step} de 6</span></footer>}</section></main>}
function Step({icon,kicker,title,text,children}:{icon:ReactNode;kicker:string;title:string;text:string;children:ReactNode}){return <div className="onboarding-step"><div className="step-icon">{icon}</div><span className="onboarding-kicker">{kicker}</span><h2>{title}</h2><p>{text}</p>{children}</div>}
function MoneyInput({value,onChange}:{value:number;onChange:(v:number)=>void}){return <div className="money-input"><span>R$</span><input type="number" inputMode="decimal" step="0.01" min="0" value={value||''} onChange={e=>onChange(Number(e.target.value))} placeholder="0,00" required/></div>}
function AddButton({busy,children}:{busy:boolean;children:ReactNode}){return <button className="onboarding-add" disabled={busy}><Plus/>{busy?'Salvando...':children}</button>}
function Continue({onClick,disabled=false,children}:{onClick:()=>void;disabled?:boolean;children:ReactNode}){return <button type="button" className="onboarding-primary full continue" onClick={onClick} disabled={disabled}>{children}<ArrowRight/></button>}
function Created({values}:{values:string[]}){if(!values.length)return null;return <div className="created-list">{values.map((x,i)=><div key={`${x}-${i}`}><Check/><span>{x}</span></div>)}</div>}
function Count({value,text}:{value:number;text:string}){if(!value)return null;return <div className="onboarding-count"><Check/> {value} {text}{value>1?'s':''}</div>}
function RecurringForm({draft,setDraft,busy,button,onSubmit}:{draft:RecurringDraft;setDraft:(d:RecurringDraft)=>void;busy:boolean;button:string;onSubmit:(e:FormEvent)=>void}){return <form onSubmit={onSubmit}><label>Descrição<input value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Ex.: Salário, Escola, Internet" required/></label><div className="onboarding-grid two"><label>Valor<MoneyInput value={draft.amount} onChange={v=>setDraft({...draft,amount:v})}/></label><label>Dia do mês<input type="number" min="1" max="28" value={draft.day} onChange={e=>setDraft({...draft,day:Number(e.target.value)})} required/></label></div><label>Categoria <small>opcional</small><input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} placeholder="Ex.: Salário, Escola, Moradia"/></label><AddButton busy={busy}>{button}</AddButton></form>}
