services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cashflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16
    container_name: cashflow-postgres
    environment:
      POSTGRES_USER: cashflow
      POSTGRES_PASSWORD: cashflow
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - cashflow_postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  launch-api:
    build:
      context: .
      dockerfile: src/Launch/1-Application/CashFlow.Launch.Api/Dockerfile
    container_name: cashflow-launch-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
    depends_on:
      - postgres
      - rabbitmq

  consolidation-api:
    build:
      context: .
      dockerfile: src/Consolidation/1-Application/CashFlow.Consolidation.Api/Dockerfile
    container_name: cashflow-consolidation-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
    depends_on:
      - postgres

  worker:
    build:
      context: .
      dockerfile: src/Worker/CashFlow.Worker/Dockerfile
    container_name: cashflow-worker
    depends_on:
      - postgres
      - rabbitmq
    restart: always

volumes:
  cashflow_postgres_data: