// <auto-generated />
using System;
using CashFlow.Consolidation.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashFlow.Consolidation.Infra.Migrations
{
    [DbContext(typeof(CashFlowConsolidationDbContext))]
    [Migration("20260521151423_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("CashFlow.Consolidation.Domain.Entities.DailyConsolidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCredits")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDebits")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DailyConsolidations");
                });
#pragma warning restore 612, 618
        }
    }
}
