// <auto-generated />
using System;
using CashFlow.Launch.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CashFlow.Launch.Infrastructure.Migrations
{
    [DbContext(typeof(CashFlowDbContext))]
    partial class CashFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CashFlow.Launch.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<decimal>("InitialBalance").HasColumnType("numeric");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<int>("Type").HasColumnType("integer");
                    b.HasKey("Id");
                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CashFlow.Launch.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<int>("Type").HasColumnType("integer");
                    b.HasKey("Id");
                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CashFlow.Launch.Domain.Entities.Entry", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<decimal>("Amount").HasColumnType("numeric");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("OccurredAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("Type").HasColumnType("integer");
                    b.HasKey("Id");
                    b.ToTable("Entries");
                });

            modelBuilder.Entity("CashFlow.Launch.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Error").HasColumnType("text");
                    b.Property<string>("Payload").IsRequired().HasColumnType("text");
                    b.Property<DateTime?>("ProcessedAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("RetryCount").HasColumnType("integer");
                    b.Property<string>("Type").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("OutboxMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
